name: Build

on: 
  push:
    branches:
      - main
      - release-*
    tags:
      - v*

env:
  MOD_NAME: CustomStartDeck

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
      - run: dotnet tool install --global tcli --version 0.1.4
      - run: dotnet build -c Release .
      - run: mkdir dist && cp bin/Release/net46/$MOD_NAME.dll dist/
      - name: Build thunderstore package
        run: tcli build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error
  prerelease:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-get-tag@v1
        id: tag
        with:
          strip_v: true
      - uses: mavrosxristoforos/get-xml-info@1.0
        id: csproj
        with:
          xml-file: ${{ env.MOD_NAME}}.csproj
          xpath: //Project/PropertyGroup/Version
      - name: Get thunderstore.toml version
        run: |
          version=$(grep "versionNumber" thunderstore.toml | cut -d" " -f3 | tr -d '"')
          echo "toml_version=$version" >> $GITHUB_ENV
      - run: |
          echo "Validating versions (tag: ${{ steps.tag.outputs.tag }}, csproj: ${{ steps.csproj.outputs.info }}, toml: ${{ env.toml_version }})"
      - name: Validate versions
        if: steps.tag.outputs.tag != steps.csproj.outputs.info || steps.tag.outputs.tag != env.toml_version
        uses: actions/github-script@v3
        with:
          script: core.setFailed('Release version mismatch!')
      - uses: actions/download-artifact@v3
        if: success()
        with:
          name: dist
          path: dist/
      - name: Prerelease
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          fail_on_unmatched_files: true
          draft: true
          generate_release_notes: true
